image: denoland/deno:alpine
stages:
 - gen

pages:
  stage: gen
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  script:
    - cd client
    - deno task build
    - cd ..
    - deno run --allow-read --allow-write .gitlab/client_compile.ts
    - mkdir public "public/$CI_COMMIT_SHORT_SHA/"
    - cd "public/$CI_COMMIT_SHORT_SHA/" && mkdir api lib route && cd ../../
    - cd server
    - cp -r api/ lib/ route/ "public/$CI_COMMIT_SHORT_SHA/"
    - cp *.json *.ts "public/$CI_COMMIT_SHORT_SHA/"
    - cd ..
    - echo "/downhost/dev/mod.ts /downhost/$CI_COMMIT_SHORT_SHA/mod.ts 302" > public/_redirects
    - echo "<html><head><title>Downhost:WIP</title></head><body></body></html>" > public/index.html
  artifacts:
    paths:
      - public
